var annotated_dup =
[
    [ "Catch", null, [
      [ "Detail", null, [
        [ "Approx", "class_catch_1_1_detail_1_1_approx.html", "class_catch_1_1_detail_1_1_approx" ],
        [ "EnumInfo", "struct_catch_1_1_detail_1_1_enum_info.html", "struct_catch_1_1_detail_1_1_enum_info" ],
        [ "IsStreamInsertable", "class_catch_1_1_detail_1_1_is_stream_insertable.html", "class_catch_1_1_detail_1_1_is_stream_insertable" ]
      ] ],
      [ "Generators", null, [
        [ "as", "struct_catch_1_1_generators_1_1as.html", null ],
        [ "ChunkGenerator", "class_catch_1_1_generators_1_1_chunk_generator.html", "class_catch_1_1_generators_1_1_chunk_generator" ],
        [ "FilterGenerator", "class_catch_1_1_generators_1_1_filter_generator.html", "class_catch_1_1_generators_1_1_filter_generator" ],
        [ "FixedValuesGenerator", "class_catch_1_1_generators_1_1_fixed_values_generator.html", "class_catch_1_1_generators_1_1_fixed_values_generator" ],
        [ "Generators", "class_catch_1_1_generators_1_1_generators.html", "class_catch_1_1_generators_1_1_generators" ],
        [ "GeneratorUntypedBase", "class_catch_1_1_generators_1_1_generator_untyped_base.html", "class_catch_1_1_generators_1_1_generator_untyped_base" ],
        [ "GeneratorWrapper", "class_catch_1_1_generators_1_1_generator_wrapper.html", "class_catch_1_1_generators_1_1_generator_wrapper" ],
        [ "IGenerator", "struct_catch_1_1_generators_1_1_i_generator.html", "struct_catch_1_1_generators_1_1_i_generator" ],
        [ "MapGenerator", "class_catch_1_1_generators_1_1_map_generator.html", "class_catch_1_1_generators_1_1_map_generator" ],
        [ "RandomFloatingGenerator", "class_catch_1_1_generators_1_1_random_floating_generator.html", "class_catch_1_1_generators_1_1_random_floating_generator" ],
        [ "RandomIntegerGenerator", "class_catch_1_1_generators_1_1_random_integer_generator.html", "class_catch_1_1_generators_1_1_random_integer_generator" ],
        [ "RangeGenerator", "class_catch_1_1_generators_1_1_range_generator.html", "class_catch_1_1_generators_1_1_range_generator" ],
        [ "RepeatGenerator", "class_catch_1_1_generators_1_1_repeat_generator.html", "class_catch_1_1_generators_1_1_repeat_generator" ],
        [ "SingleValueGenerator", "class_catch_1_1_generators_1_1_single_value_generator.html", "class_catch_1_1_generators_1_1_single_value_generator" ],
        [ "TakeGenerator", "class_catch_1_1_generators_1_1_take_generator.html", "class_catch_1_1_generators_1_1_take_generator" ]
      ] ],
      [ "Matchers", null, [
        [ "Floating", null, [
          [ "WithinAbsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher" ],
          [ "WithinUlpsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher" ]
        ] ],
        [ "Generic", null, [
          [ "PredicateMatcher", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher.html", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher" ]
        ] ],
        [ "Impl", null, [
          [ "MatchAllOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of" ],
          [ "MatchAnyOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of" ],
          [ "MatcherBase", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base" ],
          [ "MatcherMethod", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method" ],
          [ "MatcherUntypedBase", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base.html", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base" ],
          [ "MatchNotOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of" ]
        ] ],
        [ "StdString", null, [
          [ "CasedString", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher" ],
          [ "EndsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher" ],
          [ "RegexMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher" ],
          [ "StartsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher" ],
          [ "StringMatcherBase", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base" ]
        ] ],
        [ "Vector", null, [
          [ "ApproxMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher" ],
          [ "ContainsElementMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher" ],
          [ "UnorderedEqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher" ]
        ] ]
      ] ],
      [ "always_false", "struct_catch_1_1always__false.html", null ],
      [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
      [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
      [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
      [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
      [ "BenchmarkLooper", "class_catch_1_1_benchmark_looper.html", "class_catch_1_1_benchmark_looper" ],
      [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
      [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
      [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
      [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
      [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
      [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
      [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
      [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
      [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
      [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
      [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
      [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
      [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
      [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
      [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
      [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
      [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
      [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
      [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ],
      [ "is_range", "struct_catch_1_1is__range.html", "struct_catch_1_1is__range" ],
      [ "is_unique", "struct_catch_1_1is__unique.html", null ],
      [ "is_unique< T0, T1, Rest... >", "struct_catch_1_1is__unique_3_01_t0_00_01_t1_00_01_rest_8_8_8_01_4.html", null ],
      [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
      [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
      [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
      [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
      [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
      [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
      [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
      [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
      [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
      [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
      [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
      [ "not_this_one", "struct_catch_1_1not__this__one.html", null ],
      [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
      [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
      [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
      [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
      [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
      [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
      [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
      [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
      [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
      [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
      [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
      [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
      [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
      [ "StringMaker", "struct_catch_1_1_string_maker.html", "struct_catch_1_1_string_maker" ],
      [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", "struct_catch_1_1_string_maker_3_01bool_01_4" ],
      [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4" ],
      [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_5_01_4" ],
      [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", "struct_catch_1_1_string_maker_3_01char_01_4" ],
      [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4" ],
      [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01char[_s_z]_4" ],
      [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", "struct_catch_1_1_string_maker_3_01double_01_4" ],
      [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", "struct_catch_1_1_string_maker_3_01float_01_4" ],
      [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", "struct_catch_1_1_string_maker_3_01int_01_4" ],
      [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01_4" ],
      [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01long_01long_01_4" ],
      [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4" ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380" ],
      [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", "struct_catch_1_1_string_maker_3_01signed_01char_01_4" ],
      [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4" ],
      [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4" ],
      [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4" ],
      [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4" ],
      [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4" ],
      [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01_t[_s_z]_4" ],
      [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4" ],
      [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4" ],
      [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4" ],
      [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4" ],
      [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4" ],
      [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4" ],
      [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4" ],
      [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
      [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
      [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
      [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
      [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
      [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
      [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
      [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
      [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
      [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
      [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ]
    ] ],
    [ "AInteractable", "class_a_interactable.html", "class_a_interactable" ],
    [ "AMediator", "class_a_mediator.html", "class_a_mediator" ],
    [ "AObstacle", "class_a_obstacle.html", "class_a_obstacle" ],
    [ "APenguinController", "class_a_penguin_controller.html", "class_a_penguin_controller" ],
    [ "APenguinGlideGameModeBase", "class_a_penguin_glide_game_mode_base.html", "class_a_penguin_glide_game_mode_base" ],
    [ "APowerUp", "class_a_power_up.html", "class_a_power_up" ],
    [ "ASnowball", "class_a_snowball.html", "class_a_snowball" ],
    [ "ASoundManager", "class_a_sound_manager.html", "class_a_sound_manager" ],
    [ "ASpawnableObject", "class_a_spawnable_object.html", "class_a_spawnable_object" ],
    [ "ASpeedBoostGenerator", "class_a_speed_boost_generator.html", "class_a_speed_boost_generator" ],
    [ "ATempPlayer", "class_a_temp_player.html", "class_a_temp_player" ],
    [ "ATEMPpowerUp", "class_a_t_e_m_ppower_up.html", "class_a_t_e_m_ppower_up" ],
    [ "ATrackGeneratorBezier", "class_a_track_generator_bezier.html", "class_a_track_generator_bezier" ],
    [ "AUserInterfaceManager", "class_a_user_interface_manager.html", "class_a_user_interface_manager" ],
    [ "AWakParticleSystem", "class_a_wak_particle_system.html", "class_a_wak_particle_system" ],
    [ "Catch_global_namespace_dummy", "struct_catch__global__namespace__dummy.html", null ],
    [ "MeshSection", "class_mesh_section.html", "class_mesh_section" ],
    [ "PenguinGlide", "class_penguin_glide.html", "class_penguin_glide" ],
    [ "PenguinGlideEditorTarget", "class_penguin_glide_editor_target.html", "class_penguin_glide_editor_target" ],
    [ "PenguinGlideTarget", "class_penguin_glide_target.html", "class_penguin_glide_target" ],
    [ "UCollisionCameraShake", "class_u_collision_camera_shake.html", "class_u_collision_camera_shake" ],
    [ "ULocalHighscoreAccesor", "class_u_local_highscore_accesor.html", "class_u_local_highscore_accesor" ],
    [ "UPenguinSlideGameInstance", "class_u_penguin_slide_game_instance.html", "class_u_penguin_slide_game_instance" ]
];