var struct_z___construct___u_function___a_user_interface_manager___get_top_x_high_scores___statics =
[
    [ "UserInterfaceManager_eventGetTopXHighScores_Parms", "struct_z___construct___u_function___a_user_interface_manager___get_top_x_high_scores___statics_1304ac90e56efdd7702dabb87cd8072a7.html", "struct_z___construct___u_function___a_user_interface_manager___get_top_x_high_scores___statics_1304ac90e56efdd7702dabb87cd8072a7" ]
];