var struct_z___construct___u_function___a_penguin_glide_game_mode_base___set_widget_active___statics =
[
    [ "PenguinGlideGameModeBase_eventSetWidgetActive_Parms", "struct_z___construct___u_function___a_penguin_glide_game_mode_base___set_widget_active___staticsd10a2cb5d52cd0519a2ff107a8270c0c.html", "struct_z___construct___u_function___a_penguin_glide_game_mode_base___set_widget_active___staticsd10a2cb5d52cd0519a2ff107a8270c0c" ]
];