var struct_z___construct___u_function___a_user_interface_manager___get_current_speed___statics =
[
    [ "UserInterfaceManager_eventGetCurrentSpeed_Parms", "struct_z___construct___u_function___a_user_interface_manager___get_current_speed___statics_1_1_ubc346b0ed869520295c1fcbac47fc630.html", "struct_z___construct___u_function___a_user_interface_manager___get_current_speed___statics_1_1_ubc346b0ed869520295c1fcbac47fc630" ]
];