var struct_z___construct___u_function___a_snowball___on_comp_overlap___statics =
[
    [ "Snowball_eventOnCompOverlap_Parms", "struct_z___construct___u_function___a_snowball___on_comp_overlap___statics_1_1_snowball__event_on_comp_overlap___parms.html", "struct_z___construct___u_function___a_snowball___on_comp_overlap___statics_1_1_snowball__event_on_comp_overlap___parms" ]
];