var struct_z___construct___u_function___a_user_interface_manager___get_last_score___statics =
[
    [ "UserInterfaceManager_eventGetLastScore_Parms", "struct_z___construct___u_function___a_user_interface_manager___get_last_score___statics_1_1_user926d34881b3e8be3d0bccfb5d9183fea.html", "struct_z___construct___u_function___a_user_interface_manager___get_last_score___statics_1_1_user926d34881b3e8be3d0bccfb5d9183fea" ]
];